### ISSUE TITLE
Wrong username and password

### ISSUE THREAD

**Issue by zendevil** [alexanderkiel/datomic-free#19]
I'm connecting to the datomic server using the /init-db route handler that runs the function init-db. This is the relevant code:

```
(def db-uri "datomic:free://localhost:4334/humboi-creators-4?password=datomic")
(def *conn
  "Get shared connection."
  (delay (d/connect db-uri)))
(defn install-schema
  "This function expected to be called at system start up.
  Datomic schema migrations or db preinstalled data can be put into 'migrations/schema.edn'
  Every txes will be executed exactly once no matter how many times system restart."
  []
  (prn "installing schema")
  (let [schema-map (read-string (slurp "resources/migrations/schema.edn"))]
    (prn "schema map" schema-map)
    @(d/transact (force *conn) (:creator-schema schema-map))
    @(d/transact (force *conn) (:creation-schema schema-map))
    ))
(defn init-db [_]
  (prn "database created " (d/create-database db-uri))
  (try (install-schema)
       (catch Exception e (prn "installing schema" e)))
  (r/response "ok")
  )
```
And here's my docker compose file:

```
version: '3'
services:
  datomic:
    image: akiel/datomic-free
    environment:
        - ADMIN_PASSWORD="admin"
        - DATOMIC_PASSWORD="datomic"
    ports:
      - "4334-4336:4334-4336"
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
  tests:
    build:
      context: .
      dockerfile: Dockerfile_test.dev

```

However, upon making the request to init-db, I'm getting the error:

Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-171]

How to fix this?
